job:
  name: quick-start
  env_type: venv
  loop: False

tpu:
  allocation_mode: "queued-resources"    # tpu-vm | queued-resources
  accelerator: v6e-1
  name: yufeng-${tpu.accelerator}
  zone: us-east1-d
  version: v2-alpha-tpuv6e
  pricing: spot                   
  # spot | ondemand | preemptible
  startup_script: null
  tags: ["jobman", "experiment"]
  metadata:
    owner: "yufeng"
    # owner can be used to map tpus to user I think
    purpose: "testing jobman"

gcsfuse: null

ssh: null

venv:
  name: maxtext_env
  requirements_file: assets/requirements_maxtext.txt  
  python: "python3.9"  

command:
  cmd: |
    pip show jax
    pip show flax
  workers: all # int | list | "all"